plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
    id "de.undercouch.download" version "5.6.0"
    id 'com.apollographql.apollo' version '2.5.9'
}

def localProperties = new Properties()
localProperties.load(new FileInputStream(rootProject.file("local.properties")))

def mapsApiKey = localProperties.getProperty("MAPS_API_KEY")

android {
    namespace 'com.example.basakhuji'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.basakhuji"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        buildConfigField "String", "MAPS_API_KEY", "\"${mapsApiKey}\""
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding true
        buildConfig true
    }

    //GraphQl
    apollo {
        service("countries") {
            sourceFolder.set("com/example/basakhuji")
            rootPackageName.set("com.example.basakhuji")
            schemaFile.set(file("src/main/graphql/com/example/basakhuji/schema.graphqls"))
            introspection {
                endpointUrl.set("https://countries.trevorblades.com/graphql")
            }
        }
    }

    //<---NLP-->
    task downloadTestWorkVecTextClassifierModel(type: Download) {
        src 'https://storage.googleapis.com/download.tensorflow' +
                '.org/models/tflite/task_library/text_classification/android/text_classification_v2.tflite'
        dest "src/main/assets/wordvec.tflite"
        overwrite false
    }

    task downloadTestMobileBERTTextClassifierModel(type: Download) {
        src 'https://storage.googleapis.com/download.tensorflow' +
                '.org/models/tflite/task_library/text_classification/android/mobilebert.tflite'
        dest "src/main/assets/mobilebert.tflite"
        overwrite false
    }

    project.tasks.preBuild.dependsOn downloadTestMobileBERTTextClassifierModel
    project.tasks.preBuild.dependsOn downloadTestWorkVecTextClassifierModel

}

dependencies {

    implementation 'com.apollographql.apollo:apollo-runtime:2.5.9'
    implementation 'com.apollographql.apollo:apollo-rx2-support:2.5.9'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation "io.reactivex.rxjava2:rxjava:2.2.20"

    // RxJava2 support
    implementation 'com.apollographql.apollo:apollo-rx2-support:2.5.9'

    implementation 'com.google.android.gms:play-services-maps:19.0.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.android.volley:volley:1.2.1'
    implementation 'io.github.chaosleung:pinview:1.4.4'
    implementation 'com.github.bumptech.glide:glide:4.13.2'
    implementation 'com.google.android.gms:play-services-location:21.3.0'

    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'

    annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'
    implementation "androidx.cardview:cardview:1.0.0"
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation platform("com.google.firebase:firebase-bom:32.7.2")
    implementation 'com.google.firebase:firebase-auth:23.0.0'
    implementation 'com.google.firebase:firebase-firestore:25.1.0'
    implementation 'com.google.firebase:firebase-storage:21.0.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'

    implementation 'org.tensorflow:tensorflow-lite-task-text:0.4.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu-delegate-plugin:0.4.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.9.0'

    implementation 'com.github.denzcoskun:ImageSlideshow:0.1.2'
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'

}
